### ISSUE TITLE
inspired in lisp?

### ISSUE THREAD

**Issue by avelino** [tisp-lang/tisp#35]
The syntax reminds me of Lisp

**Comment by raviqqe** [comment]
Yes, it is! But, Clojure is listed in `README.md`. So, I don't know whether we should also add Lisp to the list or not.

**Comment by avelino** [comment]
I think it's important to me that I do not work with `Clojure` seems to me `Lisp` (references)

**Comment by raviqqe** [comment]
I will keep the list containing only Clojure because listing every language which Tisp is related to is infeasible. If you have any advice on better description on them, please reopen this issue.
